### PR TITLE
WIP: Separate C code into platform specific files.

### PR DESCRIPTION
**Pull request by chrBrd**
Inspired by @nyov's change I thought I might take things a little further. `lib_build.py` now uses `sys.platform` to select platform specific source files.

It works on Linux and OSX. It _should_ work for Solaris/Sun and FreeBSD (the correct files are loaded if the output of `sys.platform` contains `sunos` or `freebsd`), but both systems will need checked to ensure the output of `sys.platform` is as expected. As I don't use either of them it'd be great if someone else who does can test this; if not I'll get some VMs set up.

### CODE REVIEW

**Comment by nyov** [comment]
While I'm usually pro-modularization, I must admit I don't like the dependence on python here (`sys.platform`) to determine the C-module code to be built. Perhaps it doesn't make a difference in practice and it's just my feeling those preprocessor `ifdef`s looking more robust.
Also what you have made the darwin module, is actually the current fallthrough case. It may only be used by OSX, but why not keep the current logic and robustness.

But that's in addition to the code duplication introduced with multiple c files - the current single file isn't big enough or obscure enough to warrant it - IMO.

**Comment by novel** [comment]
FWIW, it builds and passes tests on FreeBSD-CURRENT/amd64.

**Comment by etrepum** [comment]
Using sys.platform here might make cross-compilation harder (although I have no idea if it works or not as-is, it's pretty rarely used in the Python world)

**Comment by chrBrd** [comment]
The output of `sys.platform` should be consistent. As per the [docs](https://docs.python.org/dev/library/sys.html#sys.platform):

> For Unix systems, except on Linux, this is the lowercased OS name as returned by uname -s with the first part of the version as returned by uname -r appended, e.g. 'sunos5' or 'freebsd8', at the time when Python was built.

The caveat to that is the 'except on Linux' part, due to this:

> Changed in version 3.3: On Linux, sys.platform doesn’t contain the major version anymore. It is always 'linux', instead of 'linux2' or 'linux3'. Since older Python versions include the version number, it is recommended to always use the startswith idiom presented above.

While that particular change wouldn't break what I've written (although I used `in` instead of `startswith`), it does show the API is subject to change and that there is a possibility (however small) of a breaking change being made in future. As unlikely as that is to happen it's pretty much guaranteed not to using preprocessor macros.

**Comment by chrBrd** [comment]
Factoring in cross-compilation issues I don't think any benefits this may bring are worth the potential downsides; I'm cloising the PR.

**Comment by chrBrd** [comment]
@novel - cheers for checking this out for me on FreeBSD anyway!

**Pull request closed without merging**
