### PR TITLE
Update Travis tests

### PR DESCRIPTION
**Pull request by chrBrd**
I've amended the Travis settings so the OSX builds run, and I've added builds for Linux.

Unfortunately it doesn't look like recent PyPy releases can be tested on OSX at present. The latest binaries can't be installed on the version of OSX Travis uses, and attempting to compile from source means the job exceeds Travis' 50 minute limit and the build is stopped. There are PyPy builds for Linux however.

The available Linux images from Travis are also quite old (Ubuntu 12 and 14), so there currently aren't any Python 3.7 Linux builds.

### CODE REVIEW

**Comment by chrBrd** [comment]
By the way, if you're happy with these I'd be willing to add a few more - Travis supports Docker builds, so as well as Python 3.7 in Ubuntu I can add a suite for Alpine.

**Comment by chrBrd** [comment]
No bother! :+1:

**Comment by etrepum** [comment]
Ugh this got merged to a branch that I deleted instead of master. I have to step away for a few hours, would be appreciated if you could re-create this PR on master and I'll sort it out later.

**Comment by chrBrd** [comment]
Will do.

**Pull request merged**
